import { defaultParams } from '../../params'
import { DEFAULT_FONT } from '../../fonts'
import type { ParamSpec } from '../../params'

/**
 * The 2D text layer's controls.
 *
 * Grouped, because there are forty of them and a flat list is unusable. The
 * ungrouped few at the top are the ones every use of the layer touches — what
 * it says and what it says it in; everything else is a treatment you go
 * looking for.
 *
 * Colour is expressed as an *index into the layer's palette*, never as a raw
 * hex value. That is the difference between type that sits in the artwork and
 * type that sits on top of it: swapping the palette — from the picker, from
 * remix, from a preset — recolours the words along with the picture, and a
 * stack can never drift into a colour that appears nowhere else in the frame.
 */

export const DEFAULT_TEXT = 'FRAME\nFIELD'
export const DEFAULT_PALETTE = ['#050505', '#f5f5f5', '#0057ff']
/** Six is the palette editor's ceiling; the index wraps below it. */
export const MAX_SWATCHES = 6

const swatch = (
  key: string,
  label: string,
  group: string,
  fallback: number,
): ParamSpec => ({
  kind: 'slider',
  key,
  label,
  group,
  min: 0,
  max: MAX_SWATCHES - 1,
  step: 1,
  default: fallback,
})

export const TEXT_PARAMS: Array<ParamSpec> = [
  {
    kind: 'text',
    key: 'text',
    label: 'Text',
    default: DEFAULT_TEXT,
    maxLength: 500,
    multiline: true,
  },
  { kind: 'font', key: 'font', label: 'Face', default: DEFAULT_FONT },
  {
    kind: 'select',
    key: 'case',
    label: 'Case',
    default: 'upper',
    options: [
      { value: 'as-is', label: 'As-is' },
      { value: 'upper', label: 'AA' },
      { value: 'lower', label: 'aa' },
      { value: 'title', label: 'Aa' },
    ],
  },

  /* -- Layout ----------------------------------------------------------- */
  {
    kind: 'select',
    key: 'fit',
    label: 'Fit',
    group: 'Layout',
    default: 'stretch',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'width', label: 'Width' },
      { value: 'block', label: 'Block' },
      { value: 'stretch', label: 'Flush' },
      { value: 'spread', label: 'Spread' },
    ],
  },
  {
    kind: 'slider',
    key: 'size',
    label: 'Size',
    group: 'Layout',
    min: 8,
    max: 900,
    step: 1,
    default: 190,
    spatial: true,
    unit: 'px',
  },
  {
    kind: 'slider',
    key: 'tracking',
    label: 'Tracking',
    group: 'Layout',
    min: -40,
    max: 120,
    step: 1,
    default: -4,
    spatial: true,
    unit: 'px',
  },
  {
    kind: 'slider',
    key: 'leading',
    label: 'Leading',
    group: 'Layout',
    min: 0.5,
    max: 2.4,
    step: 0.01,
    default: 0.82,
  },
  {
    kind: 'select',
    key: 'align',
    label: 'Align',
    group: 'Layout',
    default: 'center',
    options: [
      { value: 'left', label: 'Left' },
      { value: 'center', label: 'Centre' },
      { value: 'right', label: 'Right' },
    ],
  },
  {
    kind: 'select',
    key: 'valign',
    label: 'V Align',
    group: 'Layout',
    default: 'middle',
    options: [
      { value: 'top', label: 'Top' },
      { value: 'middle', label: 'Mid' },
      { value: 'bottom', label: 'Bot' },
    ],
  },

  /* -- Frame ------------------------------------------------------------ */
  {
    kind: 'slider',
    key: 'width',
    label: 'Box W',
    group: 'Frame',
    min: 16,
    max: 4096,
    step: 1,
    default: 900,
    spatial: true,
    unit: 'px',
  },
  {
    kind: 'slider',
    key: 'height',
    label: 'Box H',
    group: 'Frame',
    min: 16,
    max: 4096,
    step: 1,
    default: 620,
    spatial: true,
    unit: 'px',
  },
  {
    kind: 'slider',
    key: 'x',
    label: 'Offset X',
    group: 'Frame',
    min: -4096,
    max: 4096,
    step: 1,
    default: 0,
    spatial: true,
    unit: 'px',
  },
  {
    kind: 'slider',
    key: 'y',
    label: 'Offset Y',
    group: 'Frame',
    min: -4096,
    max: 4096,
    step: 1,
    default: 0,
    spatial: true,
    unit: 'px',
  },
  {
    kind: 'slider',
    key: 'rotate',
    label: 'Rotate',
    group: 'Frame',
    min: -180,
    max: 180,
    step: 0.5,
    default: 0,
    unit: '°',
  },

  /* -- Fill ------------------------------------------------------------- */
  {
    kind: 'palette',
    key: 'palette',
    label: 'Palette',
    group: 'Fill',
    default: DEFAULT_PALETTE,
  },
  {
    kind: 'select',
    key: 'fill',
    label: 'Fill',
    group: 'Fill',
    default: 'solid',
    options: [
      { value: 'solid', label: 'Solid' },
      { value: 'gradient', label: 'Grad' },
      { value: 'stripe', label: 'Stripe' },
      { value: 'scan', label: 'Scan' },
      { value: 'check', label: 'Check' },
      { value: 'stencil', label: 'Stencil' },
    ],
  },
  swatch('ink', 'Ink', 'Fill', 1),
  swatch('paper', 'Paper', 'Fill', 0),
  {
    kind: 'slider',
    key: 'fillAngle',
    label: 'Angle',
    group: 'Fill',
    min: 0,
    max: 360,
    step: 1,
    default: 90,
    unit: '°',
  },
  {
    kind: 'slider',
    key: 'fillScale',
    label: 'Scale',
    group: 'Fill',
    min: 2,
    max: 200,
    step: 1,
    default: 18,
    spatial: true,
    unit: 'px',
  },
  {
    kind: 'slider',
    key: 'fillDuty',
    label: 'Duty',
    group: 'Fill',
    min: 0.05,
    max: 0.95,
    step: 0.01,
    default: 0.5,
  },

  /* -- Stroke ----------------------------------------------------------- */
  {
    kind: 'select',
    key: 'stroke',
    label: 'Stroke',
    group: 'Stroke',
    default: 'off',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'outline', label: 'Out' },
      { value: 'inline', label: 'In' },
      { value: 'only', label: 'Only' },
    ],
  },
  {
    kind: 'slider',
    key: 'strokeWidth',
    label: 'Weight',
    group: 'Stroke',
    min: 1,
    max: 60,
    step: 1,
    default: 6,
    spatial: true,
    unit: 'px',
  },
  swatch('strokeInk', 'Colour', 'Stroke', 2),

  /* -- Depth ------------------------------------------------------------ */
  {
    kind: 'select',
    key: 'depth',
    label: 'Depth',
    group: 'Depth',
    default: 'off',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'extrude', label: 'Solid' },
      { value: 'shadow', label: 'Cast' },
      { value: 'echo', label: 'Echo' },
    ],
  },
  {
    kind: 'slider',
    key: 'depthSize',
    label: 'Throw',
    group: 'Depth',
    min: 0,
    max: 400,
    step: 1,
    default: 48,
    spatial: true,
    unit: 'px',
  },
  {
    kind: 'slider',
    key: 'depthAngle',
    label: 'Direction',
    group: 'Depth',
    min: 0,
    max: 360,
    step: 1,
    default: 135,
    unit: '°',
  },
  swatch('depthInk', 'Colour', 'Depth', 2),
  {
    kind: 'slider',
    key: 'depthFade',
    label: 'Fade',
    group: 'Depth',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0,
  },
  {
    kind: 'slider',
    key: 'echoCount',
    label: 'Copies',
    group: 'Depth',
    min: 1,
    max: 16,
    step: 1,
    default: 5,
  },
  {
    kind: 'slider',
    key: 'echoScale',
    label: 'Growth',
    group: 'Depth',
    min: 0.6,
    max: 1.4,
    step: 0.01,
    default: 1,
  },
  {
    kind: 'slider',
    key: 'echoRotate',
    label: 'Turn',
    group: 'Depth',
    min: -45,
    max: 45,
    step: 0.5,
    default: 0,
    unit: '°',
  },
  {
    kind: 'toggle',
    key: 'echoCycle',
    label: 'Cycle palette',
    group: 'Depth',
    default: true,
  },

  /* -- Chaos ------------------------------------------------------------ */
  { kind: 'seed', key: 'seed', label: 'Seed', group: 'Chaos', default: 'type' },
  {
    kind: 'slider',
    key: 'charShift',
    label: 'Shift',
    group: 'Chaos',
    min: 0,
    max: 120,
    step: 1,
    default: 0,
    spatial: true,
    unit: 'px',
  },
  {
    kind: 'slider',
    key: 'charTurn',
    label: 'Turn',
    group: 'Chaos',
    min: 0,
    max: 90,
    step: 0.5,
    default: 0,
    unit: '°',
  },
  {
    kind: 'slider',
    key: 'charSize',
    label: 'Size',
    group: 'Chaos',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0,
  },
  {
    kind: 'slider',
    key: 'charColour',
    label: 'Colour',
    group: 'Chaos',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0,
  },

  /* -- Warp ------------------------------------------------------------- */
  {
    kind: 'select',
    key: 'warp',
    label: 'Warp',
    group: 'Warp',
    default: 'off',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'arc', label: 'Arc' },
      { value: 'wave', label: 'Wave' },
      { value: 'bulge', label: 'Bulge' },
      { value: 'skew', label: 'Skew' },
      { value: 'persp', label: 'Persp' },
    ],
  },
  {
    kind: 'slider',
    key: 'warpAmount',
    label: 'Amount',
    group: 'Warp',
    min: -1,
    max: 1,
    step: 0.01,
    default: 0.4,
  },
  {
    kind: 'slider',
    key: 'warpFreq',
    label: 'Frequency',
    group: 'Warp',
    min: 0.25,
    max: 8,
    step: 0.25,
    default: 1.5,
  },
  {
    kind: 'slider',
    key: 'warpPhase',
    label: 'Phase',
    group: 'Warp',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0,
  },
]

export const TEXT_DEFAULTS = () => defaultParams(TEXT_PARAMS)
